config/routes.rb
RecruitingOnRails::Application.routes.draw do
  resources :candidates

end

app/models/candidate.rb
# encoding: UTF-8
require 'file_size_validator'
class Candidate < ActiveRecord::Base
  validates_presence_of :name, :message => "姓名不能为空"

  validates_presence_of :cellphone, :message => "手机号码不能为空"
  validates_numericality_of :cellphone, :message => "手机号码包含非数字", :unless => :error_for_cellphone?
  validates_uniqueness_of :cellphone, :scope => :email, :message => "手机号码已经被使用", :unless => :error_for_cellphone?
  validates_length_of :cellphone, :is=>11, :message => "手机号码长度不是11位", :unless => :error_for_cellphone?

  validates_presence_of :sex, :message => "性别不能为空"
  validates_presence_of :college, :message => "学校名称不能为空"
  validates_presence_of :major, :message => "专业不能为空"
  validates_presence_of :graduate_year, :message => "毕业年份不能为空"
  validates_presence_of :graduate_month, :message => "毕业月份不能为空"

  validates_presence_of :email, :message => "邮箱不能为空", :unless => :error_for_email?
  validates_format_of :email, :with=>/\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, :message => "邮箱格式不正确", :unless => :error_for_email?
  validates_uniqueness_of :email, :scope => :cellphone, :message => "邮箱地址已经被使用", :unless => :error_for_email?

  validates_presence_of :degree, :message => "学位不能为空"
  validates_presence_of :job_title, :message => "应聘职位不能为空"
  validates_presence_of :track_source, :message => "信息来源不能为空"

  mount_uploader :resume, ResumeUploader
  validates_presence_of :resume, :message => "简历不能为空"
  validates :resume, :presence => true, :file_size => {
      :maximum => 2.megabytes.to_i
  }

  private

  def error_for_cellphone?
    errors.has_key?(:cellphone)
  end

  def error_for_email?
    errors.has_key?(:email)
  end
end

app/models/candidate_observer.rb
class CandidateObserver < ActiveRecord::Observer
  observe :candidate

  def after_create(candidate)
    CandidateMailer.registration_confirmation(candidate).deliver
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  # GET /candidates
  # GET /candidates.json
  def index
    @candidates = Candidate.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @candidates }
    end
  end

  # GET /candidates/1
  # GET /candidates/1.json
  def show
    @candidate = Candidate.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @candidate }
    end
  end

  # GET /candidates/new
  # GET /candidates/new.json
  def new
    @candidate = Candidate.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @candidate }
    end
  end

  # GET /candidates/1/edit
  def edit
    @candidate = Candidate.find(params[:id])
  end

  # POST /candidates
  # POST /candidates.json
  def create
    @candidate = Candidate.new(params[:candidate])

    respond_to do |format|
      if @candidate.save
        format.html { redirect_to @candidate, notice: 'Candidate was successfully created.' }
        format.json { render json: @candidate, status: :created, location: @candidate }
      else
        format.html { render action: "new" }
        format.json { render json: @candidate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /candidates/1
  # PUT /candidates/1.json
  def update
    @candidate = Candidate.find(params[:id])

    respond_to do |format|
      if @candidate.update_attributes(params[:candidate])
        format.html { redirect_to @candidate, notice: 'Candidate was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @candidate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /candidates/1
  # DELETE /candidates/1.json
  def destroy
    @candidate = Candidate.find(params[:id])
    @candidate.destroy

    respond_to do |format|
      format.html { redirect_to candidates_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/candidates/_form.html.erb
<%= form_for(@candidate, :html => {:multipart => true}) do |f| %>
  <% default_select_text= "--请选择--" %>
  <%= f.hidden_field :id %>
  <fieldset>
    <%= f.label :name, "姓名" %>
    <%= f.text_field :name, :autofocus => "autofocus" %>
    <span class="error-message"><%= @candidate.errors['name'].first %></span>

    <p>请输入中文名</p>
  </fieldset>
  <fieldset>
    <%= f.label :cellphone, "手机号码" %>
    <%= f.text_field :cellphone %>
    <span class="error-message"><%= @candidate.errors['cellphone'].first %></span>

    <p>手机号码输入格式：13912345678</p>
  </fieldset>

  <fieldset>
    <%= f.label :email, "电子邮箱" %>
    <%= f.text_field :email %>
    <span class="error-message"><%= @candidate.errors['email'].first %></span>

    <p>我们会向您的邮箱发送确认邮件及后续通知邮件</p>
  </fieldset>

  <fieldset>
    <%= f.label :job_title, "应聘职位" %>
    <%= f.select :job_title, ['应用软件开发工程师', '质量保证工程师'], :include_blank => default_select_text %>
    <span class="error-message"><%= @candidate.errors['job_title'].first %></span>
  </fieldset>

  <fieldset>
    <%= f.label :sex, "性别" %>
    <%= f.select :sex, ['男', '女'], :include_blank => default_select_text %>
    <span class="error-message"><%= @candidate.errors['sex'].first %></span>
  </fieldset>

  <fieldset>
    <%= f.label :college, "毕业院校" %>
    <%= f.text_field :college %>
    <span class="error-message"><%= @candidate.errors['college'].first %></span>

    <p>请输入学校全称</p>
  </fieldset>

  <fieldset>
    <%= f.label :degree, "学位" %>
    <%= f.select :degree, ['学士', '硕士', '博士', '其他'], :include_blank => default_select_text %>
    <span class="error-message"><%= @candidate.errors['degree'].first %></span>
  </fieldset>

  <fieldset>
    <%= f.label :major, "专业" %>
    <%= f.text_field :major %>
    <span class="error-message"><%= @candidate.errors['major'].first %></span>
  </fieldset>

  <fieldset>
    <%= f.label :graduate_year, "毕业年月" %>
    <%= f.select :graduate_year, ['2009', '2010', '2011', '2012'], :include_blank => default_select_text %>
    <%= f.select :graduate_month, ['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12'], :include_blank => default_select_text %>
    <span class="error-message"><%= @candidate.errors['graduate_year'].first %></span>
    <span class="error-message"><%= @candidate.errors['graduate_month'].first %></span>
  </fieldset>

  <fieldset>
    <%= f.label :track_source, "招聘信息来源" %>
    <%= f.select :track_source, ['同学介绍', '宣讲会', '学校BBS', '招聘网站', '微博/博客', '其他'], :include_blank => default_select_text %>
    <span class="error-message"><%= @candidate.errors['track_source'].first %></span>
  </fieldset>
  <fieldset>
    <%= f.label :resume, "简历附件" %>
    <%= f.file_field(:resume, :class => 'file_input') %>
    <%= f.hidden_field(:resume_cache)%>
    <span class="error-message"><%= @candidate.errors['resume'].first %></span>
  </fieldset>
  <div class="actions">
    <%= f.submit :value=> "提交", :class => "button" %>
  </div>
<% end %>

app/views/candidates/edit.html.erb
<h1>Editing candidate</h1>

<%= render 'form' %>

<%= link_to 'Show', @candidate %>

app/views/candidates/index.html.erb
<header>
  <h1>全部候选人</h1>
</header>

<div class="content">
  <div class="data_container">
    <table id="candidates">
      <tr>
        <th>Id</th>
        <th>电话</th>
        <th>姓名</th>
        <th>性别</th>
        <th>毕业院校</th>
        <th>专业</th>
        <th>毕业时间</th>
        <th>电子邮件</th>
        <th>学位</th>
        <th>应聘职位</th>
        <th>消息来源</th>
        <th>LG正确</th>
        <th>LG答题</th>
        <th>WL正确</th>
        <th>WL答题</th>
        <th>作业提交</th>
        <th>HR面试分组</th>
        <th>HR面试结果</th>
        <th>小组面试分组</th>
        <th>小组面试结果</th>
        <th>Offer</th>
        <th>备注</th>
        <th colspan="4">简历链接</th>
      </tr>

      <% @candidates.each do |candidate| %>
        <tr>
          <td><%= candidate.id %></td>
          <td><%= candidate.cellphone %></td>
          <td><%= candidate.name %></td>
          <td><%= candidate.sex %></td>
          <td><%= candidate.college %></td>
          <td><%= candidate.major %></td>
          <td><%= candidate.graduate_year %>.<%= candidate.graduate_month %></td>
          <td><%= candidate.email %></td>
          <td><%= candidate.degree %></td>
          <td><%= candidate.job_title %></td>
          <td><%= candidate.track_source %></td>
          <td><%= candidate.lg_score %></td>
          <td><%= candidate.lg_answered %></td>
          <td><%= candidate.wl_score %></td>
          <td><%= candidate.wl_answered %></td>
          <td><%= candidate.assignment_submitted %></td>
          <td><%= candidate.hr_interview_group %></td>
          <td><%= candidate.hr_interview_result %></td>
          <td><%= candidate.team_interview_group %></td>
          <td><%= candidate.team_interview_result %></td>
          <td><%= candidate.offer %></td>
          <td><%= candidate.comment %></td>
          <td><a href="<%= candidate.resume %>">Download</a></td>
          <td><%= link_to 'Show', candidate %></td>
          <td><%= link_to 'Edit', edit_candidate_path(candidate) %></td>
          <td><%= link_to 'Destroy', candidate, :confirm => 'Are you sure?', :method => :delete %></td>
        </tr>
      <% end %>
    </table>
  </div>
  <div class="actions">
    <%= link_to 'New Candidate', new_candidate_path, :class => "button" %>
  </div>
</div>

app/views/candidates/new.html.erb
<header>
  <h1>欢迎使用ThoughtWorks简历提交系统</h1>
</header>

<div class="content" id="new">

  <img class="picture" src="/assets/advertisement-mini.png" alt="advertisement">

  <%= render 'form' %>

</div>

app/views/candidates/show.html.erb
<p id="notice"><%= notice %></p>

<ol>
  <li>
    <b>Cellphone:</b>
    <span><%= @candidate.cellphone %></span>
  </li>

  <li>
    <b>Name:</b>
    <span><%= @candidate.name %></span>
  </li>

  <li>
    <b>Sex:</b>
    <span><%= @candidate.sex %></span>
  </li>

  <li>
    <b>College:</b>
    <span><%= @candidate.college %></span>
  </li>

  <li>
    <b>Major:</b>
    <span><%= @candidate.major %></span>
  </li>

  <li>
    <b>Graduate at:</b>
    <span><%= @candidate.graduate_year %></span>
    <span><%= @candidate.graduate_month %></span>
  </li>

  <li>
    <b>Email:</b>
    <span><%= @candidate.email %></span>
  </li>

  <li>
    <b>Degree:</b>
    <span><%= @candidate.degree %></span>
  </li>

  <li>
    <b>JobTitle:</b>
    <span><%= @candidate.job_title %></span>
  </li>

  <li>
    <b>TrackSource:</b>
    <span><%= @candidate.track_source %></span>
  </li>

  <li>
    <b>Resume:</b>
    <span><%= @candidate.resume %></span>
  </li>
</ol>

<div class="actions">
  <%= link_to 'Edit', edit_candidate_path(@candidate), :class => "button" %>
  <%= link_to 'Back', candidates_path, :class => "button" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RecruitingOnRails</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>